In [2]:
import os
os.environ["TQDM_DISABLE"] = "1"  # 完全禁用进度条
import akshare as ak

In [ ]:
df_stock = ak.stock_zh_a_spot_em()

In [14]:
# 期货实时行情（指定合约）
df_futures = ak.futures_zh_spot(symbol="AU2608", market="CF")
df_futures

,symbol,time,open,high,low,current_price,bid_price,ask_price,buy_vol,sell_vol,hold,volume,avg_price,last_close,last_settle_price
0,黄金2608,023000,884.94,891.64,883.0,891.14,890.84,891.14,7,16,83392.0,79893,0.0,0.0,879.22

In [ ]:
df_futures = ak.futures_zh_spot(symbol="AU2608", market="CF")
df_futures

,symbol,time,open,high,low,current_price,bid_price,ask_price,buy_vol,sell_vol,hold,volume,avg_price,last_close,last_settle_price
0,黄金2608,023000,884.94,891.64,883.0,891.14,890.84,891.14,7,16,83392.0,79893,0.0,0.0,879.22